INSERT INTO MECHANICS VALUES ('3', 'mechanics', 'mechanicsA');
INSERT INTO MECHANICS VALUES ('4', 'mechanics', 'mechanicsB');

INSERT INTO JOBTYPE VALUES ('2', '180', 'GENERAL_CHECK');
INSERT INTO JOBTYPE VALUES ('3', '60', 'TIRE_REPLACEMENT');
INSERT INTO JOBTYPE VALUES ('4', '30', 'LAMP_CHANGE');
